logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: DEBUG
    com.example.bankcards: DEBUG
  file:
    name: log
server:
  port: 8085
spring:
  kafka:
    bootstrap-servers: localhost:9092
