spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/clientprocessing
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: none
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: DEBUG
    com.example.bankcards: DEBUG
  file:
    name: log
server:
  port: 8081