CREATE SEQUENCE IF NOT EXISTS client_products_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS clients_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS products_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_user_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE client_products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    close_date date                                    NOT NULL,
    open_date  date                                    NOT NULL,
    status     VARCHAR(128)                            NOT NULL,
    client_id  BIGINT,
    product_id BIGINT,
    CONSTRAINT client_products_pkey PRIMARY KEY (id)
);

CREATE TABLE clients
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id       VARCHAR(128)                            NOT NULL,
    date_of_birth   date                                    NOT NULL,
    document_id     VARCHAR(128)                            NOT NULL,
    document_prefix VARCHAR(128)                            NOT NULL,
    document_suffix VARCHAR(128)                            NOT NULL,
    document_type   VARCHAR(128)                            NOT NULL,
    first_name      VARCHAR(128)                            NOT NULL,
    last_name       VARCHAR(128)                            NOT NULL,
    middle_name     VARCHAR(128)                            NOT NULL,
    user_id         BIGINT,
    CONSTRAINT clients_pkey PRIMARY KEY (id)
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date date                                    NOT NULL,
    key         VARCHAR(128)                            NOT NULL,
    name        VARCHAR(128)                            NOT NULL,
    product_id  VARCHAR(255),
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(128)                            NOT NULL,
    login    VARCHAR(128)                            NOT NULL,
    password VARCHAR(128)                            NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE clients
    ADD CONSTRAINT uk2og8x0i6lngghy4cqupje9dki UNIQUE (client_id);

ALTER TABLE users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE clients
    ADD CONSTRAINT ukex6t13775jjsgit51kdsf6hxt UNIQUE (document_id);

ALTER TABLE users
    ADD CONSTRAINT ukow0gan20590jrb00upg3va2fn UNIQUE (login);

ALTER TABLE clients
    ADD CONSTRAINT uksmrp6gi0tckq1w5rnd7boyowu UNIQUE (user_id);

ALTER TABLE client_products
    ADD CONSTRAINT fk1cb4a8wh5kdwbv0g5mhll84yx FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE NO ACTION;

ALTER TABLE client_products
    ADD CONSTRAINT fk99dbqck9te9a0tjg4bl11oi6q FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE NO ACTION;

ALTER TABLE clients
    ADD CONSTRAINT fktiuqdledq2lybrds2k3rfqrv4 FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE NO ACTION;