CREATE SEQUENCE IF NOT EXISTS accounts_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cards_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS payments_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS transactions_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE accounts
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance       BIGINT                                  NOT NULL,
    card_exist    BOOLEAN                                 NOT NULL,
    client_id     BIGINT                                  NOT NULL,
    interest_rate VARCHAR(255)                            NOT NULL,
    is_recalc     BOOLEAN                                 NOT NULL,
    product_id    BIGINT                                  NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    CONSTRAINT accounts_pkey PRIMARY KEY (id)
);

CREATE TABLE cards
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    card_id        VARCHAR(16)                             NOT NULL,
    payment_system VARCHAR(255)                            NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    account_id     BIGINT,
    CONSTRAINT cards_pkey PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id   BIGINT                                  NOT NULL,
    amount       BIGINT                                  NOT NULL,
    is_credit    BOOLEAN                                 NOT NULL,
    payment_date date                                    NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id BIGINT                                  NOT NULL,
    amount     BIGINT                                  NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    timestamp  date                                    NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    card_id    BIGINT,
    CONSTRAINT transactions_pkey PRIMARY KEY (id)
);

ALTER TABLE cards
    ADD CONSTRAINT uk12a2rkq9an62uq7b1mx8551hx UNIQUE (card_id);

ALTER TABLE cards
    ADD CONSTRAINT fkdjw7dinkpc0f01yk4m57uq2u2 FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE NO ACTION;

ALTER TABLE transactions
    ADD CONSTRAINT fkjxdscq0bxpy0pl465vvsqc89j FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE NO ACTION;