spring:
  kafka:
    bootstrap-servers: localhost:9092
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: DEBUG
    com.example.bankcards: DEBUG
  file:
    name: log
server:
  port: 8082
value:
  month: 12