CREATE SEQUENCE IF NOT EXISTS payment_registry_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS product_registry_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE payment_registry
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount                  BIGINT                                  NOT NULL,
    debt_amount             BIGINT                                  NOT NULL,
    expired                 BOOLEAN                                 NOT NULL,
    interest_rate_amount    FLOAT                                   NOT NULL,
    paymend_date            date                                    NOT NULL,
    payment_expiration_date date                                    NOT NULL,
    product_registry_id     BIGINT,
    CONSTRAINT payment_registry_pkey PRIMARY KEY (id)
);

CREATE TABLE product_registry
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id    BIGINT                                  NOT NULL,
    client_id     BIGINT                                  NOT NULL,
    interest_rate BOOLEAN                                 NOT NULL,
    open_date     date                                    NOT NULL,
    product_id    BIGINT                                  NOT NULL,
    CONSTRAINT product_registry_pkey PRIMARY KEY (id)
);

ALTER TABLE payment_registry
    ADD CONSTRAINT fk14iubxr7p3xeqges2b1jex2a7 FOREIGN KEY (product_registry_id) REFERENCES product_registry (id) ON DELETE NO ACTION;